### PR TITLE
Fix #285: WiFi does not work if NVS storage on the gateway is damaged

### LINKED ISSUE #285: WiFi does not work if NVS storage on the gateway is damaged
```
I (178737) reset_task: [reset_task] System restart is activated by WiFi AP timeout
ets Jul 29 2019 12:21:46
rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:7020
load:0x40078000,len:14172
ho 0 tail 12 room 4
load:0x40080400,len:4352
entry 0x400806ec
I (72) boot: Chip Revision: 3
I (73) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (41) boot: ESP-IDF v4.0.3 2nd stage bootloader
I (41) boot: compile time 17:09:00
I (51) boot: Enabling RNG early entropy source...
I (51) boot: SPI Speed      : 40MHz
I (51) boot: SPI Mode       : DIO
I (54) boot: SPI Flash Size : 16MB
I (59) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (84) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 ota_0            OTA app          00 10 00100000 00400000
I (99) boot:  4 fatfs_gwui       Unknown data     01 81 00500000 000c0000
I (107) boot:  5 fatfs_nrf52      Unknown data     01 81 005c0000 00040000
I (114) boot:  6 ota_1            OTA app          00 11 00600000 00400000
I (122) boot:  7 fatfs_gwui_2     Unknown data     01 81 00a00000 000c0000
I (129) boot:  8 fatfs_nrf52_2    Unknown data     01 81 00ac0000 00040000
I (137) boot: End of partition table
I (141) boot_comm: chip revision: 3, min. application chip revision: 0
I (148) esp_image: segment 0: paddr=0x00100020 vaddr=0x3f400020 size=0x2fd5c (195932) map
I (228) esp_image: segment 1: paddr=0x0012fd84 vaddr=0x3ffb0000 size=0x0028c (   652) load
I (228) esp_image: segment 2: paddr=0x00130018 vaddr=0x400d0018 size=0xbcd54 (773460) map
I (511) esp_image: segment 3: paddr=0x001ecd74 vaddr=0x3ffb028c size=0x030d4 ( 12500) load
I (516) esp_image: segment 4: paddr=0x001efe50 vaddr=0x40080000 size=0x00400 (  1024) load
I (518) esp_image: segment 5: paddr=0x001f0258 vaddr=0x40080400 size=0x17190 ( 94608) load
I (580) boot: Loaded app from partition at offset 0x100000
I (580) boot: Disabling RNG early entropy source...
I (581) cpu_start: Pro cpu up.
I (584) cpu_start: Application information:
I (589) cpu_start: Project name:     ruuvi_gateway_esp
I (595) cpu_start: App version:      v1.6.0
I (600) cpu_start: Compile time:     Jul 19 2021 17:08:47
I (606) cpu_start: ELF file SHA256:  9f5d5a5665c3dfc3...
I (612) cpu_start: ESP-IDF:          v4.0.3
I (617) cpu_start: Single core mode
I (621) heap_init: Initializing. RAM available for dynamic allocation:
I (628) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (634) heap_init: At 3FFBEB88 len 00021478 (133 KiB): DRAM
I (641) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM
I (647) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
I (653) heap_init: At 40097590 len 00008A70 (34 KiB): IRAM
I (659) cpu_start: Pro cpu start user code
I (677) spi_flash: detected chip: generic
I (678) spi_flash: flash io: dio
I (678) cpu_start: Starting scheduler on PRO CPU.
I (681) fw_update: [main] Project name     : ruuvi_gateway_esp
I (687) fw_update: [main] Firmware version : v1.6.0
I (693) fw_update: [main] Currently running partition: ota_0
I (699) fw_update: [main] Next update partition: ota_1: address 0x00600000, size 0x400000
I (707) fw_update: [main] Next fatfs_gwui partition: fatfs_gwui_2: address 0x00a00000, size 0xc0000
I (717) fw_update: [main] Next fatfs_nrf52 partition: fatfs_nrf52_2: address 0x00ac0000, size 0x40000
I (729) SwitchCtrl: [main] GPIO SwitchCtrl init
I (732) gpio: GPIO[14]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (742) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 
I (751) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (760) LEDS: [main] leds_init
I (764) os_task: [main] Start thread 'leds_task' with priority 6, stack size 2048 bytes
I (773) LEDS: [leds_task] leds_task started
I (777) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (787) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
E (797) settings: [main] ../main/settings.c:32 {settings_nvs_open}: Can't open 'ruuvi_gateway' NVS namespace, err=4353 (ERROR)
W (808) settings: [main] Using default config:
I (814) gw_cfg: [main] Gateway SETTINGS:
I (818) gw_cfg: [main] config: use eth: 0
I (823) gw_cfg: [main] config: use eth dhcp: 1
I (828) gw_cfg: [main] config: eth static ip: 
I (833) gw_cfg: [main] config: eth netmask: 
I (838) gw_cfg: [main] config: eth gw: 
I (843) gw_cfg: [main] config: eth dns1: 
I (847) gw_cfg: [main] config: eth dns2: 
I (852) gw_cfg: [main] config: use mqtt: 0
I (857) gw_cfg: [main] config: mqtt server: 
I (862) gw_cfg: [main] config: mqtt port: 0
I (867) gw_cfg: [main] config: mqtt prefix: 
I (871) gw_cfg: [main] config: mqtt client id: 
I (877) gw_cfg: [main] config: mqtt user: 
I (881) gw_cfg: [main] config: mqtt password: ********
I (887) gw_cfg: [main] config: use http: 1
I (892) gw_cfg: [main] config: http url: https://network.ruuvi.com/record
I (899) gw_cfg: [main] config: http user: 
I (904) gw_cfg: [main] config: http pass: ********
I (910) gw_cfg: [main] config: LAN auth type: lan_auth_deny
I (916) gw_cfg: [main] config: LAN auth user: 
I (921) gw_cfg: [main] config: LAN auth pass: ********
I (927) gw_cfg: [main] config: coordinates: 
I (932) gw_cfg: [main] config: use company id filter: 1
I (938) gw_cfg: [main] config: company id: 0x0499
I (943) gw_cfg: [main] config: use scan coded phy: 0
I (949) gw_cfg: [main] config: use scan 1mbit/phy: 1
I (954) gw_cfg: [main] config: use scan extended payload: 1
I (961) gw_cfg: [main] config: use scan channel 37: 1
I (966) gw_cfg: [main] config: use scan channel 38: 1
I (972) gw_cfg: [main] config: use scan channel 39: 1
I (978) LEDS: [main] leds_indication_on_nrf52_fw_updating
I (984) LEDS: [main] LED: Start blinking, interval: 1000 ms, duty cycle: 5%
I (992) nRF52Fw: [main] Hardware reset nRF52: true
I (997) gpio: GPIO[17]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (1106) nRF52Fw: [main] Hardware reset nRF52: false
I (1106) nRF52Fw: [main] Init SWD
I (1106) SWD: [main] nRF52 SWD init
D (1108) SWD: [main] ../main/nrf52swd.c:120 {nrf52swd_init_spi_init}: spi_bus_initialize
D (1117) SWD: [main] ../main/nrf52swd.c:134 {nrf52swd_init_spi_add_device}: spi_bus_add_device
D (1125) SWD: [main] ../main/nrf52swd.c:194 {nrf52swd_init_internal}: libswd_init
D (1133) SWD: [main] ../main/nrf52swd.c:147 {nrf52swd_libswd_debug_init}: libswd_debug_init
D (1159) SWD: [main] ../main/nrf52swd.c:209 {nrf52swd_init_internal}: nrf52swd_init ok
D (1160) SWD: [main] ../main/nrf52swd.c:288 {nrf52swd_check_id_code}: libswd_dap_detect
I (1166) SWD: [main] IDCODE: 0x2ba01477
D (1212) FlashFatFS: [main] ../main/flashfatfs.c:44 {flashfatfs_mount}: Mount partition 'fatfs_nrf52' to the mount point /fs_nrf52
I (1215) FlashFatFS: [main] Partition 'fatfs_nrf52' mounted successfully to /fs_nrf52
I (1223) nRF52Fw: [main] Firmware on FatFS: v0.7.2
I (1240) nRF52Fw: [main] Firmware on nRF52: v0.7.2
I (1240) nRF52Fw: [main] Firmware updating is not needed
I (1240) FlashFatFS: [main] Unmount /fs_nrf52
I (1290) SWD: [main] Run nRF52 firmware
I (1316) nRF52Fw: [main] Deinit SWD
I (1316) SWD: [main] nRF52 SWD deinit
D (1316) SWD: [main] ../main/nrf52swd.c:230 {nrf52swd_deinit}: libswd_deinit
D (1322) SWD: [main] ../main/nrf52swd.c:238 {nrf52swd_deinit}: spi_bus_remove_device
D (1328) SWD: [main] ../main/nrf52swd.c:250 {nrf52swd_deinit}: spi_bus_free
I (1336) gpio: GPIO[16]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (1345) gpio: GPIO[15]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (1354) nRF52Fw: [main] Hardware reset nRF52: true
I (1460) nRF52Fw: [main] Hardware reset nRF52: false
I (1460) LEDS: [main] LED: OFF
I (1460) os_task: [main] Start thread 'adv_post_task' with priority 1, stack size 4096 bytes
I (1468) ADV_POST_TASK: [adv_post_task] adv_post_task
I (1469) ruuvi_gateway: [main] Request nRF52 ID
I (1474) ADV_POST_TASK: [adv_post_task] Advertisements in table: 0
I (1483) ADV_POST_TASK: [rx_parse_task] nRF52 DEVICE ID : 0x917a70a04cd99660
I (1492) ADV_POST_TASK: [rx_parse_task] nRF52 MAC ADDR  : 0x0000c45405eb8f34
I (1500) terminal_log: -----DEVICE_ID-----
I (1506) terminal_log: ID: 60:96:d9:4c:a0:70:7a:91
I (1512) terminal_log: ADDR: 34:8f:eb:05:54:c4:00:00
I (1579) ruuvi_gateway: [main] nRF52 DEVICE ID : 91:7A:70:A0:4C:D9:96:60
I (1579) ruuvi_gateway: [main] nRF52 ADDR      : C4:54:05:EB:8F:34
I (1583) ruuvi_gateway: [main] Mac address: C4:54:05:EB:8F:34
I (1589) ruuvi_gateway: [main] WiFi SSID / Hostname: RuuviGateway8F34
E (1596) settings: [main] ../main/settings.c:32 {settings_nvs_open}: Can't open 'ruuvi_gateway' NVS namespace, err=4353 (ERROR)
W (1608) settings: [main] Use empty mac_addr
I (1613) settings: [main] Save new MAC-address: C4:54:05:EB:8F:34
E (1620) settings: [main] ../main/settings.c:32 {settings_nvs_open}: Can't open 'ruuvi_gateway' NVS namespace, err=4353 (ERROR)
E (1632) settings: [main] ../main/settings.c:173 {settings_write_mac_addr}: settings_nvs_open failed
I (1642) os_task: [main] Start thread(static) 'time_task' with priority 1, stack size 3072 bytes
I (1651) TIME: [time_task] time_task started
I (1656) ruuvi_gateway: [main] sending settings to NRF: use filter: 1, company id: 0x0499,use scan coded phy: 0,use scan 1mbit/phy: 1,use scan extended payload: 1,use scan channel 37: 1,use scan channel 38: 1,use scan channel 39: 1
D (1677) FlashFatFS: [main] ../main/flashfatfs.c:44 {flashfatfs_mount}: Mount partition 'fatfs_gwui' to the mount point /fs_gwui
I (1691) FlashFatFS: [main] Partition 'fatfs_gwui' mounted successfully to /fs_gwui
I (1697) wifi_manager: [main] WiFi manager init
I (1703) wifi_manager: [main] Set STA IP String to: 0.0.0.0
I (1709) http_server: [main] Start HTTP-Server
I (1714) os_task: [main] Start thread 'http_server' with priority 4, stack size 20480 bytes
I (1715) terminal_log: -----ACK-----
I (1725) http_server: [http_server] HTTP-Server thread started
I (1734) http_server: [http_server] HTTP Server listening on 80/tcp
I (1742) terminal_log: CMD: RE_CA_UART_SET_ALL
I (1745) wifi_manager: [main] WiFi manager init: start WiFi
I (1748) terminal_log: ACK state: RE_CA_ACK_OK
I (1755) wifi_init: rx ba win: 6
I (1761) wifi_init: tcpip mbox: 32
I (1765) wifi_init: udp mbox: 6
I (1769) wifi_init: tcp mbox: 6
I (1773) wifi_init: tcp tx win: 5744
I (1777) wifi_init: tcp rx win: 5744
I (1782) wifi_init: tcp mss: 1440
I (1786) wifi_init: WiFi IRAM OP enabled
I (1790) wifi_init: WiFi RX IRAM OP enabled
E (1795) wifi_manager: [main] ../components/esp32-wifi-manager/src/wifi_manager.c:231 {wifi_manager_init_start_wifi}: esp_wifi_init failed
E (1808) wifi_manager: [main] ../components/esp32-wifi-manager/src/wifi_sta_config.c:157 {wifi_sta_nvs_open}: Can't open 'espwifimgr' NVS namespace, err=4353 (ERROR)
E (1824) wifi_manager: [main] ../components/esp32-wifi-manager/src/wifi_sta_config.c:309 {wifi_sta_config_do_fetch}: wifi_sta_nvs_open failed
E (1837) wifi_manager: [main] ../components/esp32-wifi-manager/src/wifi_sta_config.c:336 {wifi_sta_config_fetch}: wifi_sta_config_do_fetch failed
I (1851) wifi_manager: [main] No saved wifi found on startup. Starting access point.
I (1859) ETH: [main] Ethernet init
I (1863) ETH: [main] Using ETH DHCP
I (1868) ETH: [main] ETH ip updated
I (1873) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1902) ETH: [main] Ethernet start
I (1912) ETH: [sys_evt] Ethernet Started
I (1912) ETH: [main] Set hostname for Ethernet interface: RuuviGateway8F34
I (1913) LEDS: [main] leds_indication_network_no_connection
I (1920) LEDS: [main] LED: Start blinking, interval: 200 ms, duty cycle: 50%
I (1928) os_task: [main] Start thread 'monitoring_task' with priority 1, stack size 2048 bytes
I (1937) os_task: [main] Start thread 'reset_task' with priority 1, stack size 4096 bytes
I (1937) ruuvi_gateway: [monitoring_task] free heap: 176968
I (1946) ruuvi_gateway: [main] Main started
I (1946) reset_task: [reset_task] Reset task started
```

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Review by ojousima — APPROVED** [review]
Thanks

**Comment by DG12** [comment]
Can you describe "damaged".  Are you referring to a hardware malfunction /non-function?
Or are you referring to "corruption" as in values left over ? 
Or do you mean like Junk/garbage/ totally invalid and unexpected vaules.

**Comment by ojousima** [comment]
> Or do you mean like Junk/garbage/ totally invalid and unexpected values.

This

**Comment by TheSomeMan** [comment]
> Can you describe "damaged". Are you referring to a hardware malfunction /non-function?
> Or are you referring to "corruption" as in values left over ?
> Or do you mean like Junk/garbage/ totally invalid and unexpected values.

@DG12 In version 1.4.0 the NVS format has been slightly changed and in some cases NVS initialization fails due to garbage in the data.

**Comment by TheSomeMan** [comment]
> Can you describe "damaged". Are you referring to a hardware malfunction /non-function?
> Or are you referring to "corruption" as in values left over ?
> Or do you mean like Junk/garbage/ totally invalid and unexpected values.

@DG12 In version 1.4.0 the NVS format has been slightly changed and in some cases NVS initialization fails due to garbage in the data.

**Pull request merged**
