### PR TITLE
#141: Update README.md (flashing using esptool or Windows GUI tool)

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Comment by ojousima** [comment]
This pull request has quite a bit more than just a readme update, is this intentional?

**Comment by TheSomeMan** [comment]
> This pull request has quite a bit more than just a readme update, is this intentional?

All previous commits except the last one was already merged to the master. I'm not sure why github does not show it.

**Comment by TheSomeMan** [comment]
Here is the previous pull request: https://github.com/ruuvi/ruuvi.gateway_esp.c/pull/142

**Comment by ojousima** [comment]
Ok. Would this be a good time to add instructions on how to make the nRF52 binary for flashing?

**Comment by TheSomeMan** [comment]
> Ok. Would this be a good time to add instructions on how to make the nRF52 binary for flashing?

fatfs_nrf52.bin is generated automatically when you execute 'idf.py build', it downloads compiled firmware from https://github.com/ruuvi/ruuvi.gateway_nrf.c/releases/download/v0.5.0/ruuvigw_nrf_armgcc_ruuvigw_release_v0.5.0_full.hex and converts it for FAT-FS image.

**Review by ojousima — APPROVED** [review]
Thanks

**Pull request merged**
