### PR TITLE
Close #958: Handle empty response on /firmwareupate request

### LINKED ISSUE #958: Handle empty response on /firmwareupate request

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Comment by ojousima** [comment]
How much effort it would be to add unit tests for empty / invalid firmware update info?

**Comment by TheSomeMan** [comment]
> How much effort it would be to add unit tests for empty / invalid firmware update info?

I think it'll take a couple of hours

**Review by ojousima — APPROVED** [review]
Thanks, getting the test coverage to 80 % isn't strictly necessary if the tests already cover most edge cases

**Comment by TheSomeMan** [comment]
> Thanks, getting the test coverage to 80 % isn't strictly necessary if the tests already cover most edge cases

I added some more tests to check how updating is working for beta testers.

**Comment by TheSomeMan** [comment]
@markoaamunkajo to test it you can use script ruuvi.gwui.html/scripts/http_server_auth.py, run it on your computer, then in UI on "Software Update" page enter URL in the "Server for automatic firmware updates":
* http://<YOUR_IP>:8000/firmwareupdate
* http://<YOUR_IP>:8000/firmwareupdate_beta
* http://<YOUR_IP>:8000/firmwareupdate_not_exist
* http://<YOUR_IP>:8000/firmwareupdate_empty

**Pull request merged**
