### PR TITLE
#755: Update Ruuvi Gateway configuration guide for advanced users

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Review by ojousima — APPROVED** [review]
Thanks

**Comment by TheSomeMan** [comment]
@markoaamunkajo This configuration guide is located in the project repo: docs/gateway_configuration/gateway_configuration.md

**Comment by markoaamunkajo** [comment]
@TheSomeMan made some minor changes and sent back to you for review.

**Comment by markoaamunkajo** [comment]
QA passed

**Pull request merged**
