### PR TITLE
Configure GitHub actions

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Review by ojousima — APPROVED** [review]
Thanks, if I'm reading this correctly the build is done on GitHub and artifacts are stored in GitHub as well?

**Comment by TheSomeMan** [comment]
> Thanks, if I'm reading this correctly the build is done on GitHub and artifacts are stored in GitHub as well?

Yes, that's right, now the artifacts are stored on GitHub, but they are also built on the Jenkins server. I removed all actions like executing Google tests and Sonar cloud checks from Jenkins, all that's left is the firmware build. For building/storing artifacts, we can choose between Jenkins or GitHub or keep both.

**Comment by TheSomeMan** [comment]
@markoaamunkajo This task does not involve any code modification. Now formatting checks, running Google Tests, SonarCloud checks are done in GitHub Actions instead of Jenkins. Building firmware binary files is done in both Jenkins and GitHub Actions.

**Comment by markoaamunkajo** [comment]
Nothing to QA

**Pull request merged**
