### PR TITLE
Close #988: Clear all saved TLS session tickets on URL validation or after saving configuration

### LINKED ISSUE #988: Clear all saved TLS session tickets on URL validation or after saving configuration

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Review by ojousima — APPROVED** [review]
Thanks

**Comment by ojousima** [comment]
See #988

**Comment by TheSomeMan** [comment]
For testing, you need to analyze the logs during URL validation.

**Comment by markoaamunkajo** [comment]
QA passed

**Pull request merged**
